### ISSUE TITLE
Remove seeds from iCloud

### ISSUE THREAD

**Issue by f0go** [Terra-Planet/iOS#31]
Will remove seeds from iCloud and save them encrypted locally. Saving only the password in iCloud to keep using face id

**Comment by eaceto** [comment]
Dismissed. 

Security Level is **This device only**

https://github.com/eaceto/Terra-Planet.iOS/blob/38500cfd01d761d30e3deba72d716f8d551199cc/Terra%20Planet/API/KeyChainManager.swift#L21
