### ISSUE TITLE
Add Toast after the address is copied into the clipboard

### ISSUE THREAD

**Issue by nfmelendez** [Terra-Planet/iOS#7]
Add Toast after the address is copied into the clipboard.
For example in Belo:
![IMG_2653 3](https://user-images.githubusercontent.com/726950/160482287-7c197c2f-c51a-4ba5-8c54-d66830dfd820.jpg)

**Comment by f0go** [comment]
I will add a haptic feedback

**Comment by f0go** [comment]
https://github.com/Terra-Planet/iOS/commit/93188d9bf979c4b70ecd28e0709ba602fa062994
